/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-09-18 03:56:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Registration</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<form action=\"User_info\" method=\"POST\">\n");
      out.write("\t<h2 style=\"color:green; text-align:center;\">Register</h2>\n");
      out.write("\t<table style = \"border:1px solid; margin: 0 auto; text-align:center;\">\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t\t<td>First Name :</td>\n");
      out.write("\t\t\t<td><input required=\"required\" type=\"text\" name=\"firstName\" autofocus /></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t\t<td>Last Name :</td>\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"lastName\" required/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t\t<td>Address :</td>\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"address\" required/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t\t<td>Email :</td>\n");
      out.write("\t\t\t<td><input type=\"email\" name=\"email\" required/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t\t<td>Username :</td>\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"userName\" required/></td>\n");
      out.write("\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserNameMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t\t<td>Password :</td>\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"password\" required/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t\t<td>Phone Number :</td>\n");
      out.write("\t\t\t<td><input type=\"tel\" name=\"phoneNo\" required/></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t<td>Country</td>\n");
      out.write("    <td><select name=\"country\" required>\n");
      out.write("\t\t<option value=\"\">Country...</option>\n");
      out.write("\t\t<option value=\"Afganistan\">Afghanistan</option>\n");
      out.write("\t\t<option value=\"Albania\">Albania</option>\n");
      out.write("\t\t<option value=\"Algeria\">Algeria</option>\n");
      out.write("\t\t<option value=\"American Samoa\">American Samoa</option>\n");
      out.write("\t\t<option value=\"Andorra\">Andorra</option>\n");
      out.write("\t\t<option value=\"Angola\">Angola</option>\n");
      out.write("\t\t<option value=\"Anguilla\">Anguilla</option>\n");
      out.write("\t\t<option value=\"Antigua &amp; Barbuda\">Antigua &amp; Barbuda</option>\n");
      out.write("\t\t<option value=\"Argentina\">Argentina</option>\n");
      out.write("\t\t<option value=\"Armenia\">Armenia</option>\n");
      out.write("\t\t<option value=\"Aruba\">Aruba</option>\n");
      out.write("\t\t<option value=\"Australia\">Australia</option>\n");
      out.write("\t\t<option value=\"Austria\">Austria</option>\n");
      out.write("\t\t<option value=\"Azerbaijan\">Azerbaijan</option>\n");
      out.write("\t\t<option value=\"Bahamas\">Bahamas</option>\n");
      out.write("\t\t<option value=\"Bahrain\">Bahrain</option>\n");
      out.write("\t\t<option value=\"Bangladesh\">Bangladesh</option>\n");
      out.write("\t\t<option value=\"Barbados\">Barbados</option>\n");
      out.write("\t\t<option value=\"Belarus\">Belarus</option>\n");
      out.write("\t\t<option value=\"Belgium\">Belgium</option>\n");
      out.write("\t\t<option value=\"Belize\">Belize</option>\n");
      out.write("\t\t<option value=\"Benin\">Benin</option>\n");
      out.write("\t\t<option value=\"Bermuda\">Bermuda</option>\n");
      out.write("\t\t<option value=\"Bhutan\">Bhutan</option>\n");
      out.write("\t\t<option value=\"Bolivia\">Bolivia</option>\n");
      out.write("\t\t<option value=\"Bonaire\">Bonaire</option>\n");
      out.write("\t\t<option value=\"Bosnia &amp; Herzegovina\">Bosnia &amp; Herzegovina</option>\n");
      out.write("\t\t<option value=\"Botswana\">Botswana</option>\n");
      out.write("\t\t<option value=\"Brazil\">Brazil</option>\n");
      out.write("\t\t<option value=\"British Indian Ocean Ter\">British Indian Ocean Ter</option>\n");
      out.write("\t\t<option value=\"Brunei\">Brunei</option>\n");
      out.write("\t\t<option value=\"Bulgaria\">Bulgaria</option>\n");
      out.write("\t\t<option value=\"Burkina Faso\">Burkina Faso</option>\n");
      out.write("\t\t<option value=\"Burundi\">Burundi</option>\n");
      out.write("\t\t<option value=\"Cambodia\">Cambodia</option>\n");
      out.write("\t\t<option value=\"Cameroon\">Cameroon</option>\n");
      out.write("\t\t<option value=\"Canada\">Canada</option>\n");
      out.write("\t\t<option value=\"Canary Islands\">Canary Islands</option>\n");
      out.write("\t\t<option value=\"Cape Verde\">Cape Verde</option>\n");
      out.write("\t\t<option value=\"Cayman Islands\">Cayman Islands</option>\n");
      out.write("\t\t<option value=\"Central African Republic\">Central African Republic</option>\n");
      out.write("\t\t<option value=\"Chad\">Chad</option>\n");
      out.write("\t\t<option value=\"Channel Islands\">Channel Islands</option>\n");
      out.write("\t\t<option value=\"Chile\">Chile</option>\n");
      out.write("\t\t<option value=\"China\">China</option>\n");
      out.write("\t\t<option value=\"Christmas Island\">Christmas Island</option>\n");
      out.write("\t\t<option value=\"Cocos Island\">Cocos Island</option>\n");
      out.write("\t\t<option value=\"Colombia\">Colombia</option>\n");
      out.write("\t\t<option value=\"Comoros\">Comoros</option>\n");
      out.write("\t\t<option value=\"Congo\">Congo</option>\n");
      out.write("\t\t<option value=\"Cook Islands\">Cook Islands</option>\n");
      out.write("\t\t<option value=\"Costa Rica\">Costa Rica</option>\n");
      out.write("\t\t<option value=\"Cote DIvoire\">Cote D'Ivoire</option>\n");
      out.write("\t\t<option value=\"Croatia\">Croatia</option>\n");
      out.write("\t\t<option value=\"Cuba\">Cuba</option>\n");
      out.write("\t\t<option value=\"Curaco\">Curacao</option>\n");
      out.write("\t\t<option value=\"Cyprus\">Cyprus</option>\n");
      out.write("\t\t<option value=\"Czech Republic\">Czech Republic</option>\n");
      out.write("\t\t<option value=\"Denmark\">Denmark</option>\n");
      out.write("\t\t<option value=\"Djibouti\">Djibouti</option>\n");
      out.write("\t\t<option value=\"Dominica\">Dominica</option>\n");
      out.write("\t\t<option value=\"Dominican Republic\">Dominican Republic</option>\n");
      out.write("\t\t<option value=\"East Timor\">East Timor</option>\n");
      out.write("\t\t<option value=\"Ecuador\">Ecuador</option>\n");
      out.write("\t\t<option value=\"Egypt\">Egypt</option>\n");
      out.write("\t\t<option value=\"El Salvador\">El Salvador</option>\n");
      out.write("\t\t<option value=\"Equatorial Guinea\">Equatorial Guinea</option>\n");
      out.write("\t\t<option value=\"Eritrea\">Eritrea</option>\n");
      out.write("\t\t<option value=\"Estonia\">Estonia</option>\n");
      out.write("\t\t<option value=\"Ethiopia\">Ethiopia</option>\n");
      out.write("\t\t<option value=\"Falkland Islands\">Falkland Islands</option>\n");
      out.write("\t\t<option value=\"Faroe Islands\">Faroe Islands</option>\n");
      out.write("\t\t<option value=\"Fiji\">Fiji</option>\n");
      out.write("\t\t<option value=\"Finland\">Finland</option>\n");
      out.write("\t\t<option value=\"France\">France</option>\n");
      out.write("\t\t<option value=\"French Guiana\">French Guiana</option>\n");
      out.write("\t\t<option value=\"French Polynesia\">French Polynesia</option>\n");
      out.write("\t\t<option value=\"French Southern Ter\">French Southern Ter</option>\n");
      out.write("\t\t<option value=\"Gabon\">Gabon</option>\n");
      out.write("\t\t<option value=\"Gambia\">Gambia</option>\n");
      out.write("\t\t<option value=\"Georgia\">Georgia</option>\n");
      out.write("\t\t<option value=\"Germany\">Germany</option>\n");
      out.write("\t\t<option value=\"Ghana\">Ghana</option>\n");
      out.write("\t\t<option value=\"Gibraltar\">Gibraltar</option>\n");
      out.write("\t\t<option value=\"Great Britain\">Great Britain</option>\n");
      out.write("\t\t<option value=\"Greece\">Greece</option>\n");
      out.write("\t\t<option value=\"Greenland\">Greenland</option>\n");
      out.write("\t\t<option value=\"Grenada\">Grenada</option>\n");
      out.write("\t\t<option value=\"Guadeloupe\">Guadeloupe</option>\n");
      out.write("\t\t<option value=\"Guam\">Guam</option>\n");
      out.write("\t\t<option value=\"Guatemala\">Guatemala</option>\n");
      out.write("\t\t<option value=\"Guinea\">Guinea</option>\n");
      out.write("\t\t<option value=\"Guyana\">Guyana</option>\n");
      out.write("\t\t<option value=\"Haiti\">Haiti</option>\n");
      out.write("\t\t<option value=\"Hawaii\">Hawaii</option>\n");
      out.write("\t\t<option value=\"Honduras\">Honduras</option>\n");
      out.write("\t\t<option value=\"Hong Kong\">Hong Kong</option>\n");
      out.write("\t\t<option value=\"Hungary\">Hungary</option>\n");
      out.write("\t\t<option value=\"Iceland\">Iceland</option>\n");
      out.write("\t\t<option value=\"India\">India</option>\n");
      out.write("\t\t<option value=\"Indonesia\">Indonesia</option>\n");
      out.write("\t\t<option value=\"Iran\">Iran</option>\n");
      out.write("\t\t<option value=\"Iraq\">Iraq</option>\n");
      out.write("\t\t<option value=\"Ireland\">Ireland</option>\n");
      out.write("\t\t<option value=\"Isle of Man\">Isle of Man</option>\n");
      out.write("\t\t<option value=\"Israel\">Israel</option>\n");
      out.write("\t\t<option value=\"Italy\">Italy</option>\n");
      out.write("\t\t<option value=\"Jamaica\">Jamaica</option>\n");
      out.write("\t\t<option value=\"Japan\">Japan</option>\n");
      out.write("\t\t<option value=\"Jordan\">Jordan</option>\n");
      out.write("\t\t<option value=\"Kazakhstan\">Kazakhstan</option>\n");
      out.write("\t\t<option value=\"Kenya\">Kenya</option>\n");
      out.write("\t\t<option value=\"Kiribati\">Kiribati</option>\n");
      out.write("\t\t<option value=\"Korea North\">Korea North</option>\n");
      out.write("\t\t<option value=\"Korea Sout\">Korea South</option>\n");
      out.write("\t\t<option value=\"Kuwait\">Kuwait</option>\n");
      out.write("\t\t<option value=\"Kyrgyzstan\">Kyrgyzstan</option>\n");
      out.write("\t\t<option value=\"Laos\">Laos</option>\n");
      out.write("\t\t<option value=\"Latvia\">Latvia</option>\n");
      out.write("\t\t<option value=\"Lebanon\">Lebanon</option>\n");
      out.write("\t\t<option value=\"Lesotho\">Lesotho</option>\n");
      out.write("\t\t<option value=\"Liberia\">Liberia</option>\n");
      out.write("\t\t<option value=\"Libya\">Libya</option>\n");
      out.write("\t\t<option value=\"Liechtenstein\">Liechtenstein</option>\n");
      out.write("\t\t<option value=\"Lithuania\">Lithuania</option>\n");
      out.write("\t\t<option value=\"Luxembourg\">Luxembourg</option>\n");
      out.write("\t\t<option value=\"Macau\">Macau</option>\n");
      out.write("\t\t<option value=\"Macedonia\">Macedonia</option>\n");
      out.write("\t\t<option value=\"Madagascar\">Madagascar</option>\n");
      out.write("\t\t<option value=\"Malaysia\">Malaysia</option>\n");
      out.write("\t\t<option value=\"Malawi\">Malawi</option>\n");
      out.write("\t\t<option value=\"Maldives\">Maldives</option>\n");
      out.write("\t\t<option value=\"Mali\">Mali</option>\n");
      out.write("\t\t<option value=\"Malta\">Malta</option>\n");
      out.write("\t\t<option value=\"Marshall Islands\">Marshall Islands</option>\n");
      out.write("\t\t<option value=\"Martinique\">Martinique</option>\n");
      out.write("\t\t<option value=\"Mauritania\">Mauritania</option>\n");
      out.write("\t\t<option value=\"Mauritius\">Mauritius</option>\n");
      out.write("\t\t<option value=\"Mayotte\">Mayotte</option>\n");
      out.write("\t\t<option value=\"Mexico\">Mexico</option>\n");
      out.write("\t\t<option value=\"Midway Islands\">Midway Islands</option>\n");
      out.write("\t\t<option value=\"Moldova\">Moldova</option>\n");
      out.write("\t\t<option value=\"Monaco\">Monaco</option>\n");
      out.write("\t\t<option value=\"Mongolia\">Mongolia</option>\n");
      out.write("\t\t<option value=\"Montserrat\">Montserrat</option>\n");
      out.write("\t\t<option value=\"Morocco\">Morocco</option>\n");
      out.write("\t\t<option value=\"Mozambique\">Mozambique</option>\n");
      out.write("\t\t<option value=\"Myanmar\">Myanmar</option>\n");
      out.write("\t\t<option value=\"Nambia\">Nambia</option>\n");
      out.write("\t\t<option value=\"Nauru\">Nauru</option>\n");
      out.write("\t\t<option value=\"Nepal\">Nepal</option>\n");
      out.write("\t\t<option value=\"Netherland Antilles\">Netherland Antilles</option>\n");
      out.write("\t\t<option value=\"Netherlands\">Netherlands (Holland, Europe)</option>\n");
      out.write("\t\t<option value=\"Nevis\">Nevis</option>\n");
      out.write("\t\t<option value=\"New Caledonia\">New Caledonia</option>\n");
      out.write("\t\t<option value=\"New Zealand\">New Zealand</option>\n");
      out.write("\t\t<option value=\"Nicaragua\">Nicaragua</option>\n");
      out.write("\t\t<option value=\"Niger\">Niger</option>\n");
      out.write("\t\t<option value=\"Nigeria\">Nigeria</option>\n");
      out.write("\t\t<option value=\"Niue\">Niue</option>\n");
      out.write("\t\t<option value=\"Norfolk Island\">Norfolk Island</option>\n");
      out.write("\t\t<option value=\"Norway\">Norway</option>\n");
      out.write("\t\t<option value=\"Oman\">Oman</option>\n");
      out.write("\t\t<option value=\"Pakistan\">Pakistan</option>\n");
      out.write("\t\t<option value=\"Palau Island\">Palau Island</option>\n");
      out.write("\t\t<option value=\"Palestine\">Palestine</option>\n");
      out.write("\t\t<option value=\"Panama\">Panama</option>\n");
      out.write("\t\t<option value=\"Papua New Guinea\">Papua New Guinea</option>\n");
      out.write("\t\t<option value=\"Paraguay\">Paraguay</option>\n");
      out.write("\t\t<option value=\"Peru\">Peru</option>\n");
      out.write("\t\t<option value=\"Phillipines\">Philippines</option>\n");
      out.write("\t\t<option value=\"Pitcairn Island\">Pitcairn Island</option>\n");
      out.write("\t\t<option value=\"Poland\">Poland</option>\n");
      out.write("\t\t<option value=\"Portugal\">Portugal</option>\n");
      out.write("\t\t<option value=\"Puerto Rico\">Puerto Rico</option>\n");
      out.write("\t\t<option value=\"Qatar\">Qatar</option>\n");
      out.write("\t\t<option value=\"Republic of Montenegro\">Republic of Montenegro</option>\n");
      out.write("\t\t<option value=\"Republic of Serbia\">Republic of Serbia</option>\n");
      out.write("\t\t<option value=\"Reunion\">Reunion</option>\n");
      out.write("\t\t<option value=\"Romania\">Romania</option>\n");
      out.write("\t\t<option value=\"Russia\">Russia</option>\n");
      out.write("\t\t<option value=\"Rwanda\">Rwanda</option>\n");
      out.write("\t\t<option value=\"St Barthelemy\">St Barthelemy</option>\n");
      out.write("\t\t<option value=\"St Eustatius\">St Eustatius</option>\n");
      out.write("\t\t<option value=\"St Helena\">St Helena</option>\n");
      out.write("\t\t<option value=\"St Kitts-Nevis\">St Kitts-Nevis</option>\n");
      out.write("\t\t<option value=\"St Lucia\">St Lucia</option>\n");
      out.write("\t\t<option value=\"St Maarten\">St Maarten</option>\n");
      out.write("\t\t<option value=\"St Pierre &amp; Miquelon\">St Pierre &amp; Miquelon</option>\n");
      out.write("\t\t<option value=\"St Vincent &amp; Grenadines\">St Vincent &amp; Grenadines</option>\n");
      out.write("\t\t<option value=\"Saipan\">Saipan</option>\n");
      out.write("\t\t<option value=\"Samoa\">Samoa</option>\n");
      out.write("\t\t<option value=\"Samoa American\">Samoa American</option>\n");
      out.write("\t\t<option value=\"San Marino\">San Marino</option>\n");
      out.write("\t\t<option value=\"Sao Tome &amp; Principe\">Sao Tome &amp; Principe</option>\n");
      out.write("\t\t<option value=\"Saudi Arabia\">Saudi Arabia</option>\n");
      out.write("\t\t<option value=\"Senegal\">Senegal</option>\n");
      out.write("\t\t<option value=\"Serbia\">Serbia</option>\n");
      out.write("\t\t<option value=\"Seychelles\">Seychelles</option>\n");
      out.write("\t\t<option value=\"Sierra Leone\">Sierra Leone</option>\n");
      out.write("\t\t<option value=\"Singapore\">Singapore</option>\n");
      out.write("\t\t<option value=\"Slovakia\">Slovakia</option>\n");
      out.write("\t\t<option value=\"Slovenia\">Slovenia</option>\n");
      out.write("\t\t<option value=\"Solomon Islands\">Solomon Islands</option>\n");
      out.write("\t\t<option value=\"Somalia\">Somalia</option>\n");
      out.write("\t\t<option value=\"South Africa\">South Africa</option>\n");
      out.write("\t\t<option value=\"Spain\">Spain</option>\n");
      out.write("\t\t<option value=\"Sri Lanka\">Sri Lanka</option>\n");
      out.write("\t\t<option value=\"Sudan\">Sudan</option>\n");
      out.write("\t\t<option value=\"Suriname\">Suriname</option>\n");
      out.write("\t\t<option value=\"Swaziland\">Swaziland</option>\n");
      out.write("\t\t<option value=\"Sweden\">Sweden</option>\n");
      out.write("\t\t<option value=\"Switzerland\">Switzerland</option>\n");
      out.write("\t\t<option value=\"Syria\">Syria</option>\n");
      out.write("\t\t<option value=\"Tahiti\">Tahiti</option>\n");
      out.write("\t\t<option value=\"Taiwan\">Taiwan</option>\n");
      out.write("\t\t<option value=\"Tajikistan\">Tajikistan</option>\n");
      out.write("\t\t<option value=\"Tanzania\">Tanzania</option>\n");
      out.write("\t\t<option value=\"Thailand\">Thailand</option>\n");
      out.write("\t\t<option value=\"Togo\">Togo</option>\n");
      out.write("\t\t<option value=\"Tokelau\">Tokelau</option>\n");
      out.write("\t\t<option value=\"Tonga\">Tonga</option>\n");
      out.write("\t\t<option value=\"Trinidad &amp; Tobago\">Trinidad &amp; Tobago</option>\n");
      out.write("\t\t<option value=\"Tunisia\">Tunisia</option>\n");
      out.write("\t\t<option value=\"Turkey\">Turkey</option>\n");
      out.write("\t\t<option value=\"Turkmenistan\">Turkmenistan</option>\n");
      out.write("\t\t<option value=\"Turks &amp; Caicos Is\">Turks &amp; Caicos Is</option>\n");
      out.write("\t\t<option value=\"Tuvalu\">Tuvalu</option>\n");
      out.write("\t\t<option value=\"Uganda\">Uganda</option>\n");
      out.write("\t\t<option value=\"Ukraine\">Ukraine</option>\n");
      out.write("\t\t<option value=\"United Arab Erimates\">United Arab Emirates</option>\n");
      out.write("\t\t<option value=\"United Kingdom\">United Kingdom</option>\n");
      out.write("\t\t<option value=\"United States of America\">United States of America</option>\n");
      out.write("\t\t<option value=\"Uraguay\">Uruguay</option>\n");
      out.write("\t\t<option value=\"Uzbekistan\">Uzbekistan</option>\n");
      out.write("\t\t<option value=\"Vanuatu\">Vanuatu</option>\n");
      out.write("\t\t<option value=\"Vatican City State\">Vatican City State</option>\n");
      out.write("\t\t<option value=\"Venezuela\">Venezuela</option>\n");
      out.write("\t\t<option value=\"Vietnam\">Vietnam</option>\n");
      out.write("\t\t<option value=\"Virgin Islands (Brit)\">Virgin Islands (Brit)</option>\n");
      out.write("\t\t<option value=\"Virgin Islands (USA)\">Virgin Islands (USA)</option>\n");
      out.write("\t\t<option value=\"Wake Island\">Wake Island</option>\n");
      out.write("\t\t<option value=\"Wallis &amp; Futana Is\">Wallis &amp; Futana Is</option>\n");
      out.write("\t\t<option value=\"Yemen\">Yemen</option>\n");
      out.write("\t\t<option value=\"Zaire\">Zaire</option>\n");
      out.write("\t\t<option value=\"Zambia\">Zambia</option>\n");
      out.write("\t\t<option value=\"Zimbabwe\">Zimbabwe</option>\n");
      out.write("\t</select>\n");
      out.write("\t</td>\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("\t<tr>\n");
      out.write("    \t<td><input type=\"submit\" name=\"register\" value=\"submit\"/></td>\n");
      out.write("  \t</tr>\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\n");
      out.write("\t</table>\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
